// Certificate showcase — files live in /public/assets/certificates
// Optional: drop a PNG thumbnail at /public/assets/certificates/thumbs/<same-name>.png
//   to make PDFs render instantly. If missing, we fall back to live PDF preview.
const BASE = "/assets/certificates";
const THUMB = `${BASE}/thumbs`;

// Categories drive filter chips + accent color tinting
export const certificateCategories = {
  ai:       { label: "AI & GenAI",   color: "#a78bfa" },
  cloud:    { label: "Cloud",        color: "#f59e0b" },
  dev:      { label: "Development",  color: "#e85d75" },
  data:     { label: "Data & Security", color: "#22d3ee" },
  tools:    { label: "Tools",        color: "#f472b6" },
  lang:     { label: "Language",     color: "#60a5fa" },
  award:    { label: "Awards",       color: "#34d399" },
};

export const certificates = [
  {
    title: "Anthropic Claude Architect",
    issuer: "Anthropic",
    issuerKey: "anthropic",
    category: "ai",
    year: 2025,
    file: `${BASE}/Anthropic Claude Architect.pdf`,
    thumb: `${THUMB}/Anthropic Claude Architect.png`,
    type: "pdf",
    featured: true,
  },
  {
    title: "AWS Academy Graduate",
    issuer: "Amazon Web Services",
    issuerKey: "aws",
    category: "cloud",
    year: 2024,
    file: `${BASE}/AWS Academy Graduate.pdf`,
    thumb: `${THUMB}/AWS Academy Graduate.png`,
    type: "pdf",
    featured: true,
  },
  {
    title: "AWS Serverless Badge Assessment",
    issuer: "Amazon Web Services",
    issuerKey: "aws",
    category: "cloud",
    year: 2024,
    file: `${BASE}/AWS Serverless Badge Assessment.pdf`,
    thumb: `${THUMB}/AWS Serverless Badge Assessment.png`,
    type: "pdf",
  },
  {
    title: "Enactus National Cup — Winner",
    issuer: "Enactus India",
    issuerKey: "enactus",
    category: "award",
    year: 2024,
    file: `${BASE}/Enactus National Cup Winner.png`,
    type: "image",
    featured: true,
  },
  {
    title: "EPAM Sadhaka Program",
    issuer: "EPAM Systems",
    issuerKey: "epam",
    category: "dev",
    year: 2024,
    file: `${BASE}/EPAM Sadhaka Program.pdf`,
    thumb: `${THUMB}/EPAM Sadhaka Program.png`,
    type: "pdf",
  },
  {
    title: "GenAI Prompt Engineering Basics",
    issuer: "Coursera",
    issuerKey: "coursera",
    category: "ai",
    year: 2024,
    file: `${BASE}/GenAi Prompt Engineering Basics.pdf`,
    thumb: `${THUMB}/GenAi Prompt Engineering Basics.png`,
    type: "pdf",
  },
  {
    title: "Generative AI Fundamentals",
    issuer: "IBM / Coursera",
    issuerKey: "ibm",
    category: "ai",
    year: 2024,
    file: `${BASE}/GenAI.pdf`,
    thumb: `${THUMB}/GenAI.png`,
    type: "pdf",
  },
  {
    title: "German Communicative Proficiency",
    issuer: "KIIT School of Languages",
    issuerKey: "kiit",
    category: "lang",
    year: 2023,
    file: `${BASE}/German Proficiency.pdf`,
    thumb: `${THUMB}/German Proficiency.png`,
    type: "pdf",
  },
  {
    title: "Prompt Engineering for ChatGPT",
    issuer: "Vanderbilt / Coursera",
    issuerKey: "vanderbilt",
    category: "ai",
    year: 2024,
    file: `${BASE}/Prompt Engineering for ChatGPT.pdf`,
    thumb: `${THUMB}/Prompt Engineering for ChatGPT.png`,
    type: "pdf",
  },
  {
    title: "Salesforce Developer Superbadges",
    issuer: "Salesforce",
    issuerKey: "salesforce",
    category: "dev",
    year: 2023,
    file: `${BASE}/Salesforce.pdf`,
    thumb: `${THUMB}/Salesforce.png`,
    type: "pdf",
  },
  {
    title: "Atlassian Confluence Fundamentals",
    issuer: "Atlassian",
    issuerKey: "atlassian",
    category: "tools",
    year: 2024,
    file: `${BASE}/Confluence.pdf`,
    thumb: `${THUMB}/Confluence.png`,
    type: "pdf",
  },
  {
    title: "Atlassian Jira Fundamentals",
    issuer: "Atlassian",
    issuerKey: "atlassian",
    category: "tools",
    year: 2024,
    file: `${BASE}/Jira.pdf`,
    thumb: `${THUMB}/Jira.png`,
    type: "pdf",
  },
  {
    title: "Cyber Security Essentials",
    issuer: "Cisco / Coursera",
    issuerKey: "cisco",
    category: "data",
    year: 2024,
    file: `${BASE}/Cyber Security.pdf`,
    thumb: `${THUMB}/Cyber Security.png`,
    type: "pdf",
  },
  {
    title: "Data Science Trainee Program",
    issuer: "TechBrain",
    issuerKey: "techbrain",
    category: "data",
    year: 2023,
    file: `${BASE}/Data Science.jpg`,
    type: "image",
  },
  {
    title: "Full Stack Development",
    issuer: "Webskitters Academy",
    issuerKey: "webskitters",
    category: "dev",
    year: 2022,
    file: `${BASE}/Webskitters.png`,
    type: "image",
  },
];
