export const experience = [
  {
    role: "Junior Software Engineer",
    company: "EPAM Systems",
    location: "Hyderabad, India",
    type: "On-site",
    period: "Jan 2026 – Present",
    color: "#e63946",
    current: true,
    points: [
      "Strengthened full-stack development expertise through guided training on React, Angular, and Node.js.",
      "Explored foundational AWS services to design and build reliable, scalable applications.",
      "Developed and deployed CRUD applications following modern web development best practices.",
      "Enhanced understanding of clean code methodologies and design patterns to improve code quality and maintainability.",
      "Actively participating in onboarding activities and knowledge-sharing sessions, accelerating integration and skill development.",
      "Contributing to internal EPAM initiatives, mastering company development practices, coding standards, and workflows.",
    ],
  },
  {
    role: "Junior Software Developer Intern",
    company: "EPAM Systems",
    location: "Hyderabad, India",
    type: "On-site",
    period: "Jan 2025 – Dec 2025",
    color: "#e63946",
    current: false,
    points: [
      "Developed scalable full-stack features for enterprise-grade applications.",
      "Built React.js (TypeScript) components following design system standards.",
      "Integrated REST APIs using Node.js & Express.js.",
      "Worked with AWS services including S3 and DynamoDB.",
      "Used JIRA in an Agile/Scrum environment for sprint planning and delivery.",
      "Applied software design patterns for maintainable, scalable code.",
    ],
  },
  {
    role: "Virtual Developer Intern",
    company: "Salesforce",
    location: "Remote",
    type: "Remote",
    period: "May 2024 – Jun 2024",
    color: "#00a1e0",
    current: false,
    points: [
      "Worked on Salesforce development & administration modules.",
      "Built Lightning Web Components (LWC) for custom UI solutions.",
      "Performed API integrations within the Salesforce ecosystem.",
      "Earned Superbadges: Apex Specialist, Process Automation Specialist, Developer Super Set.",
    ],
  },
  {
    role: "Full Stack Developer Intern",
    company: "HP India",
    location: "Kolkata, India",
    type: "Hybrid",
    period: "May 2023 – Sep 2023",
    color: "#0096d6",
    current: false,
    points: [
      "Built responsive UI using HTML, CSS, JavaScript, Bootstrap, and jQuery.",
      "Developed backend solutions using PHP & MySQL.",
      "Improved database query performance by 35%.",
      "Managed web hosting infrastructure with 99.9% uptime.",
    ],
  },
];
