export const personalInfo = {
  name: "Rohit Ghosh",
  title: "Full Stack Developer",
  email: "rht.ghs10@gmail.com",
  phone: "+91 8276072126",
  location: "Kolkata, West Bengal, India",
  currentRole: "Junior Software Developer @ EPAM Systems",
  experience: "3+ Years in Full Stack Development",
  summary:
    "Full-stack developer who turns complex problems into clean, scalable solutions. From cloud-native backends to pixel-perfect frontends — I build software that works and looks good doing it.",
  github: "https://github.com/rohit1682",
  linkedin: "https://www.linkedin.com/in/rohit-ghosh-b7b5201a6/",
  leetcode: "https://leetcode.com/u/rohitG33/",
  profileImage: "/assets/images/profile.jpg",
  coverImage: "/assets/images/front_cover.jpg",
  photos: {
    profile: "/assets/images/profile.jpg",
    profile2: "/assets/images/profile2.jpg",
    cover: "/assets/images/front_cover.jpg",
    intro: "/assets/images/intro.jpg",
  },
  typedRoles: [
    "Full Stack Developer",
    "Software Developer",
    "React Developer",
    "Java Developer",
    "Public Speaker",
    "Photographer",
  ],
  spokenLanguages: ["English", "German (basic), Hindi (native), Bengali (native)"],
  interests: ["Photography", "Finance", "Cricket", "Badminton", "Martial Arts"],
  currentlyLearning: ["Angular", "Advanced Node.js", "AWS"],
  tagline: "Full Stack Developer & Public Speaker",
  degree: "B.Tech — CSE, KIIT",
  status: "Open to Opportunities",

  heroGreeting: "Hi, I'm",
  heroPrimaryCTA: "View My Work",
  heroSecondaryCTA: "Say Hello",

  aboutTitle: "About Me",
  skillsTitle: "Skills",
  experienceTitle: "Experience",
  educationTitle: "Education",
  projectsTitle: "Projects",
  achievementsTitle: "Achievements",
  certificatesTitle: "Certificates",
  hobbiesTitle: "Beyond the Code",
  contactTitle: "Get In Touch",

  preloaderWords: ["Code.", "Build.", "Ship."],

  skillsTabs: { proficiency: "Proficiency", all: "All Skills" },
  projectFilters: { all: "All", featured: "⭐ Featured", more: "More" },
  featuredLabel: "Featured",
  downloadCVLabel: "Download CV",
  backToTopLabel: "Top",

  aboutIntro:
    "I'm a full-stack developer who turns complex problems into clean, scalable solutions. From cloud-native backends to pixel-perfect frontends — I build software that works and looks good doing it.",
  aboutTagline: "The developer behind the code.",
  skillsTagline: "The tools behind the craft.",
  experienceTagline: "Where I've shipped real code.",
  educationTagline: "The foundation that started it all.",
  projectsTagline: "Selected work & explorations.",
  achievementsTagline: "Moments that shaped the journey.",
  certificatesTagline: "Validated expertise. Continuous growth.",
  hobbiesTagline: "Beyond the code.",

  contactTagline: "Have a project in mind or just want to say hi? My inbox is always open.",
  contactHeading: "Let's build something.",
  contactDescription:
    "Got a project in mind? Let's talk. I'm always open to new opportunities and interesting collaborations. I usually reply within a day.",
  footerTagline: "Crafted with React, Three.js, and too much coffee.",

  marqueeItems: [
    "React", "Node.js", "TypeScript", "AWS", "Azure", "Java", "Spring Boot",
    "PostgreSQL", "MongoDB", "Docker", "Kubernetes", "GraphQL", "Redis",
    "Three.js", "Next.js", "NestJS", "Vite", "Tailwind CSS", "BigCommerce",
  ],
};
