export const projects = [
  {
    id: 1,
    color: "linear-gradient(135deg, #b91c2e 0%, #e85d75 50%, #f59e6b 100%)",
    title: "Energy-X",
    subtitle: "Gym Management Platform",
    description:
      "A full-stack gym management system with member tracking, workout plans, and administrative tools, deployed on AWS cloud infrastructure.",
    tags: ["React (TypeScript)", "Node.js", "Express", "MongoDB", "AWS"],
    github: "https://github.com/rohit1682/gym-app-serverless",
    live: "#",
    featured: true,
    status: "Completed",
    features: [
      "Member registration & profiles",
      "Workout scheduling & slot booking",
      "Role-based access control",
      "Cloud deployment (AWS S3 + DynamoDB)",
      "Unit testing with JEST",
      "Analytics & reporting dashboard",
    ],
  },
  {
    id: 2,
    color: "linear-gradient(135deg, #7c1d2e 0%, #b91c2e 50%, #e85d75 100%)",
    title: "DoConnect",
    subtitle: "Technical Q&A Platform",
    description:
      "A moderated technical Q&A platform where developers ask questions, share knowledge, and grow together — with admin-controlled content approval and role-based access.",
    tags: ["Angular", "ASP.NET", "SQL Server", "JWT", "xUnit"],
    github: "https://github.com/rohit1682/Project-DoConnect",
    live: "#",
    featured: true,
    status: "Completed",
    features: [
      "Admin-moderated content approval workflow",
      "JWT authentication with User & Admin roles",
      "Image attachments on questions & answers",
      "Full-text search across topics",
      "21 unit tests with xUnit + Moq",
    ],
  },
  {
    id: 7,
    color: "linear-gradient(135deg, #1a1a2e 0%, #b91c2e 50%, #e85d75 100%)",
    title: "Interview Slot Booking API",
    subtitle: "Production-Ready Hiring Backend",
    description:
      "A production-grade backend service that manages interview slots and candidate bookings with role-based access, conflict-safe scheduling, and MongoDB transactions to prevent overbooking under concurrency.",
    tags: ["Node.js", "Express", "MongoDB", "Mongoose", "Joi", "Swagger / OpenAPI"],
    github: "https://github.com/rohit1682/interview-app",
    live: "#",
    featured: true,
    status: "Completed",
    features: [
      "Role-based auth (Admin / Candidate) with simulated x-user-id header",
      "Slot overlap detection (partial, inside, covering)",
      "Capacity-safe booking via MongoDB transactions (no race conditions)",
      "Filtering, pagination & availability computed dynamically",
      "Joi request validation with consistent error envelope",
      "Full Swagger / OpenAPI 3.0 documentation at /docs",
    ],
  },
  {
    id: 3,
    color: "linear-gradient(135deg, #2d1b4e 0%, #b91c2e 50%, #f59e6b 100%)",
    title: "ResuNova",
    subtitle: "AI Resume Builder",
    description:
      "An intelligent resume builder that leverages AI text enhancers to create professional, ATS-optimized resumes automatically.",
    tags: ["React", "Node.js", "MongoDB", "AI Integration"],
    github: "#",
    live: "#",
    featured: true,
    status: "In Progress",
    features: [
      "AI-powered content enhancement",
      "Multiple professional templates",
      "Real-time preview & editing",
      "ATS optimization algorithms",
      "Skills matching & suggestions",
    ],
  },
  {
    id: 4,
    color: "linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)",
    title: "Diabetic Retinopathy Classification",
    subtitle: "ML / Deep Learning",
    description:
      "ML model to classify diabetic retinopathy severity from eye MRI scans using deep learning and classical ML approaches.",
    tags: ["PyTorch", "CNN", "SVM", "Random Forest", "Python"],
    github: "https://github.com/rohit1682/Project-Diabethic_Retinopathy_Classification",
    live: "#",
    featured: false,
    status: "Completed",
    features: ["CNN-based classification", "SVM & Random Forest comparison", "MRI scan preprocessing"],
  },
  {
    id: 5,
    color: "linear-gradient(135deg, #1a0a2e 0%, #7c1d2e 50%, #b91c2e 100%)",
    title: "CvGenie",
    subtitle: "AI Chatbot Resume Generator",
    description:
      "AI chatbot-based resume generator that helps users build professional resumes through a conversational interface.",
    tags: ["Django REST", "Botpress", "HTML", "CSS", "JS", "MySQL"],
    github: "https://github.com/rohit1682/CvGenie",
    live: "#",
    featured: false,
    status: "Completed",
    features: ["AI chatbot integration", "Dynamic resume generation", "PDF export", "MySQL storage"],
  },
  {
    id: 6,
    color: "linear-gradient(135deg, #1a1a1a 0%, #4a1a2a 50%, #b91c2e 100%)",
    title: "WeCare",
    subtitle: "Clothing Donation Platform",
    description:
      "Clothing donation platform connecting donors with NGOs and individuals in need, with location-based matching.",
    tags: ["HTML", "CSS", "JavaScript", "PHP", "MySQL"],
    github: "https://github.com/rohit1682/Project-WeCare",
    live: "#",
    featured: false,
    status: "Completed",
    features: ["Donor-NGO matching", "Location-based search", "Admin dashboard"],
  },
];
